# Generated by Django 3.0.5 on 2020-09-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrijemeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grad',
            name='naziv',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
