# Generated by Django 3.0.5 on 2020-09-20 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vrijemeApp', '0002_auto_20200920_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('grad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vrijemeApp.Grad')),
            ],
        ),
    ]
