# Generated by Django 3.0.5 on 2020-09-20 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vrijemeApp', '0003_korisnik'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='korisnik',
            options={'verbose_name_plural': 'korisnici'},
        ),
    ]
