# Generated by Django 3.0.5 on 2020-09-20 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vrijemeApp', '0004_auto_20200920_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnik',
            name='grad',
        ),
        migrations.AddField(
            model_name='korisnik',
            name='grad_naziv',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='korisnik',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
